name: Verify changed pact

on:
  repository_dispatch:
    types:
      - pact_changed

env:
  PACT_BROKER_BASE_URL: https://viscountdefenestrateltd.pactflow.io/ 
  PACT_BROKER_TOKEN: ${{ secrets.PACTFLOW_TOKEN }}
  PACT_BROKER_PUBLISH_VERIFICATION_RESULTS: true
  TRAVIS_COMMIT: ${{ github.sha }}
  TRAVIS_BRANCH: ${{ github.ref }}
  PACT_URL: ${{ github.event.client_payload.pact_url }}

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.x'
      # - run: docker pull pactfoundation/pact-cli:latest
      # - name: Install
      #   run: npm i
      - name: Verify
        run: TRAVIS_BRANCH=${TRAVIS_BRANCH:11} make test_webhook 